[workspace]
resolver = "2"
members = ["crates/*"]
package.edition = "2021"
package.rust-version = "1.80.0"
package.license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "=1.0.194", features = ["derive"] }